import { APIRequestContext } from '@playwright/test';
import * as fs from 'fs';
import { createSchema } from 'genson-js';
import Ajv from 'ajv';
import { expect } from '@fixtures';
import { API_SETTINGS } from '../api-settings';
export class BaseController {
  protected request: APIRequestContext;
  protected baseUrl: string;
  protected schemaPath: string;
  protected openAPIPath: string;
  protected defaultHeaders: Record<string, string>;
  protected version: string;

  constructor(request: APIRequestContext, options?: ControllerOptions) {
    this.request = request;
    this.baseUrl = options.baseUrl;
    this.schemaPath = options.schemaPath;
    this.openAPIPath = options.openAPIPath;
    this.defaultHeaders = options.defaultHeaders;
    this.version = options.version;
  }
  protected mergeHeaders(headers: Record<string, string>) {
    return { ...this.defaultHeaders, ...headers };
  }

  private createSchema(apiName: string, data: any) {
    const path = this.schemaPath + apiName;
    const schema = createSchema(data);
    const schemaString = JSON.stringify(schema, null, 3);
    try {
      fs.writeFile(path + '.json', schemaString, function (err) {
        if (err) {
          console.log(err);
        }
      });
    } catch (err) {
      console.error(err);
    }
  }
  async validateSchema(name: string, data: any) {
    if (API_SETTINGS.skipSchemaValidation == 'true') {
      return;
    }
    const schema = this.schemaPath + name + '.json';
    if (fs.existsSync(schema)) {
      const ajv = new Ajv();
      const validate = ajv.compile(this.getJson(schema));
      const valid = validate(data);
      if (!valid) console.log(validate.errors);
      expect(valid, JSON.stringify(validate.errors)).toEqual(true);
    } else {
      this.createSchema(name, data);
      expect(
        true,
        `\nWARNING!!!!!! Schema was not found at:\n${schema}\nWe autogenerated it for you, please check if it's correct.`
      ).toEqual(false);
    }
  }
  getJson(path: string): Object {
    return JSON.parse(fs.readFileSync(path, 'utf8'));
  }
}

interface ControllerOptions {
  baseUrl: string;
  schemaPath?: string;
  openAPIPath?: string;
  defaultHeaders?: Record<string, string>;
  version?: string;
  filengy?: boolean;
}
